# Generated by Django 4.1.4 on 2023-04-14 13:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='resized1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[770, 500], upload_to=''),
        ),
        migrations.AddField(
            model_name='newspost',
            name='resized2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[370, 279], upload_to=''),
        ),
        migrations.AddField(
            model_name='newspost',
            name='resized3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[271, 193], upload_to=''),
        ),
        migrations.AddField(
            model_name='newspost',
            name='resized4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[100, 70], upload_to=''),
        ),
        migrations.AddField(
            model_name='newspost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
