# Generated by Django 4.1.4 on 2023-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0003_alter_newspost_date_alter_newspost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
