# Generated by Django 4.1.4 on 2023-04-14 22:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0004_alter_newspost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='resized5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[70, 70], upload_to=''),
        ),
    ]
