# Generated by Django 4.1.4 on 2023-04-15 07:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0005_newspost_resized5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='resized2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[370, 279], upload_to=''),
        ),
    ]
