# Generated by Django 4.1.4 on 2023-04-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0006_alter_newspost_resized2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='resized1',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='resized2',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='resized3',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='resized4',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='resized5',
        ),
    ]
