# Generated by Django 4.1.4 on 2023-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0007_remove_newspost_resized1_remove_newspost_resized2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
