# Generated by Django 4.1.4 on 2023-04-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0008_newspost_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='text',
            new_name='paragraph1',
        ),
        migrations.RenameField(
            model_name='newspost',
            old_name='text2',
            new_name='paragraph2',
        ),
    ]
