# Generated by Django 4.1.4 on 2023-05-10 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newspost', '0009_rename_text_newspost_paragraph1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.RenameModel(
            old_name='NewsPost',
            new_name='NewsPostModel',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
    ]
