# Generated by Django 4.1.4 on 2023-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('photo', models.ImageField(upload_to='avatar/')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('confirmpassword', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
